import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {randomBytes} from 'node:crypto';
const require=createRequire(import.meta.url),mfRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=mfRequire('miniflare');
const bootstrap=randomBytes(32).toString('hex');
const modulePaths=readdirSync('dist/server',{recursive:true}).filter(f=>f.endsWith('.js'));const modules=['index.js',...modulePaths.filter(f=>f!=='index.js')].map(path=>({type:'ESModule',path:resolve('dist/server',path)}));
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{BOOTSTRAP_TOKEN:bootstrap,BOOTSTRAP_OWNER_EMAIL:'owner@test.invalid'},log:undefined});
const base='https://icvsp.test';
const results=[];
const check=(name,fn)=>Promise.resolve().then(fn).then(()=>{results.push({name,status:'passed'});console.log('PASS',name);});
const passwords={malak:randomBytes(16).toString('hex'),shahy:randomBytes(16).toString('hex'),member:randomBytes(16).toString('hex'),changed:randomBytes(16).toString('hex')};
let malak='',shahy='',member='',memberId='',task='',week='',month='',milestone='',meeting='',action='',review='',update='',document='';
async function req(path,{method='GET',body,cookie='',expected=200,extraHeaders={}}={}){const headers={Origin:base,...(cookie?{Cookie:cookie}:{}),...extraHeaders};if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';let payload=body?JSON.stringify(body):undefined;if(body instanceof FormData){const encoded=new Request(base+path,{method,headers,body});headers['Content-Type']=encoded.headers.get('content-type');payload=new Uint8Array(await encoded.arrayBuffer());}const res=await mf.dispatchFetch(base+path,{method,headers,body:payload});let data;const contentType=res.headers.get('content-type')||'';if(contentType.includes('json'))data=await res.json();else data=await res.arrayBuffer();assert.equal(res.status,expected,`${method} ${path}: ${res.status}, ${typeof data==='object'?JSON.stringify(data):data}`);return {res,data};}
const post=(path,body,cookie,expected=200)=>req(path,{method:'POST',body,cookie,expected});
const create=async(type,body,cookie=malak)=>(await post('/api/entities/'+type,body,cookie,201)).data.id;
try{
 const database=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const statement of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(statement.trim())await database.prepare(statement.trim()).run();
 await check('Anonymous users cannot read workspace, documents or export',async()=>{await req('/api/workspace',{expected:401});await req('/api/export',{expected:401});await req('/api/documents/not-a-document',{expected:401});});
 await check('Cross-origin and invalid activation rejected',async()=>{await post('/api/auth/bootstrap',{token:'invalid',malakEmail:'malak@test.invalid',shahyEmail:'shahy@test.invalid',malakPassword:passwords.malak,shahyPassword:passwords.shahy},'',403);const res=await mf.dispatchFetch(base+'/api/auth/login',{method:'POST',headers:{Origin:'https://other.test','Content-Type':'application/json'},body:'{}'});assert.equal(res.status,403);});
 await check('Owner-only activation page uses ChatGPT sign-in',async()=>{const r=await req('/setup');assert(new TextDecoder().decode(r.data).includes('/signin-with-chatgpt'));const wrong=await req('/setup',{extraHeaders:{'oai-authenticated-user-id':'wrong-user','oai-authenticated-user-email':'wrong@test.invalid'}});assert(new TextDecoder().decode(wrong.data).includes('Access Denied'));const correct=await req('/setup',{extraHeaders:{'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@test.invalid'}});assert.equal(correct.res.status,200);});
 await check('Two initial admin accounts and one-use activation',async()=>{const r=await post('/api/auth/bootstrap',{token:bootstrap,malakEmail:'malak@test.invalid',shahyEmail:'shahy@test.invalid',malakPassword:passwords.malak,shahyPassword:passwords.shahy});malak=r.res.headers.get('set-cookie').split(';')[0];const ws=(await req('/api/workspace',{cookie:malak})).data;assert.equal(ws.users.length,2);assert(ws.users.every(u=>u.role==='ADMIN'&&u.locked_admin===1));await post('/api/auth/bootstrap',{token:bootstrap,malakEmail:'malak@test.invalid',shahyEmail:'shahy@test.invalid',malakPassword:passwords.malak,shahyPassword:passwords.shahy},'',409);});
 await check('Malak and Shahy authenticate with secure cookies',async()=>{for(const name of ['malak','shahy']){const r=await post('/api/auth/login',{login:name,password:passwords[name],remember:true});const setCookie=r.res.headers.get('set-cookie');assert(setCookie.includes('HttpOnly')&&setCookie.includes('Secure')&&setCookie.includes('SameSite=Strict'));if(name==='malak')malak=setCookie.split(';')[0];else shahy=setCookie.split(';')[0];assert.equal((await req('/api/workspace',{cookie:setCookie.split(';')[0]})).data.user.role,'ADMIN');}});
 await check('Admin protection and temporary member password flow',async()=>{const malakUser=(await req('/api/workspace',{cookie:malak})).data.user;await req('/api/entities/users/'+malakUser.id,{method:'PATCH',cookie:shahy,body:{role:'MEMBER'},expected:400});memberId=await create('users',{name:'Integration Member',username:'testmember',email:'member@test.invalid',role:'MEMBER',active:1,password:passwords.member});const r=await post('/api/auth/login',{login:'testmember',password:passwords.member});member=r.res.headers.get('set-cookie').split(';')[0];assert((await req('/api/workspace',{cookie:member})).data.force_password);const changed=await post('/api/auth/password',{current:passwords.member,password:passwords.changed},member);member=changed.res.headers.get('set-cookie').split(';')[0];assert.equal((await req('/api/workspace',{cookie:member})).data.user.role,'MEMBER');});
 await check('Member cannot manage users, settings, Admin analytics or export',async()=>{await post('/api/entities/tasks',{},member,400);await post('/api/entities/users',{},member,403);await req('/api/entities/settings/project',{method:'PATCH',body:{phase:'bad'},cookie:member,expected:403});await req('/api/export',{cookie:member,expected:403});const r=await req('/admin/users',{cookie:member});assert(new TextDecoder().decode(r.data).includes('Access Denied'));});
 await check('Opt-in editable sample data and duplicate prevention',async()=>{await post('/api/workspace',{operation:'seed'},malak);const ws=(await req('/api/workspace',{cookie:malak})).data;assert.equal(ws.tasks.length,11);assert.equal(ws.stages.length,11);assert(ws.users.filter(u=>['ahmed','sara'].includes(u.username)).every(u=>u.active===0));await post('/api/workspace',{operation:'seed'},malak,409);const sample=ws.users.find(u=>u.username==='ahmed');await req('/api/entities/users/'+sample.id,{method:'PATCH',cookie:malak,body:{email:'ahmed@test.invalid',active:1},expected:400});});
 await check('Monthly plan, weekly plan and milestone persist',async()=>{month=await create('months',{title:'Test month',goal:'Integration tests',start_date:'2026-10-01',deadline:'2026-10-31'});week=await create('weeks',{title:'Test week',goal:'Validate workflows',start_date:'2026-10-04',deadline:'2026-10-10',month_id:month});milestone=await create('milestones',{title:'Validated milestone',deadline:'2026-10-31',month_id:month,status:'In Progress'});});
 const taskBody={title:'Integration task',description:'Task lifecycle test',assignee_id:memberId,start_date:'2026-10-04',deadline:'2026-10-10',duration:3,priority:'High',status:'To Do',progress:0,week_id:week,month_id:month,milestone_id:milestone};
 await check('Create, assign, update, comment and complete task',async()=>{task=await create('tasks',taskBody);await req('/api/entities/tasks/'+task,{method:'PATCH',cookie:member,body:{status:'In Progress',progress:50}});await create('comments',{task_id:task,body:'Testing @shahy'},member);await req('/api/entities/tasks/'+task,{method:'PATCH',cookie:member,body:{assignee_id:memberId},expected:400});const other=await create('tasks',{...taskBody,title:'Other member task',assignee_id:(await req('/api/workspace',{cookie:shahy})).data.user.id});await req('/api/entities/tasks/'+other,{method:'PATCH',cookie:member,body:{progress:25},expected:403});await req('/api/entities/tasks/'+task,{method:'PATCH',cookie:member,body:{status:'Completed',progress:80,result:'Validated'}});assert.equal((await req('/api/workspace',{cookie:malak})).data.tasks.find(t=>t.id===task).progress,100);});
 await check('Weekly updates, immutable review snapshots and carry forward history',async()=>{update=await create('updates',{week_id:week,task_id:task,description:'Completed integration testing'},member);review=await create('reviews',{week_id:week,lessons:'RBAC enforced',delay_reason:'',carry_forward:'Open follow-up task'});await req('/api/entities/reviews/'+review,{method:'PATCH',cookie:malak,body:{lessons:'rewrite'},expected:400});const next=await create('weeks',{title:'Next week',goal:'Follow-up',start_date:'2026-10-11',deadline:'2026-10-17',month_id:month});const unfinished=await create('tasks',{...taskBody,title:'Carry-forward task'});await post('/api/workspace',{operation:'carry-forward',week_id:next,task_ids:[unfinished]},malak);const ws=(await req('/api/workspace',{cookie:malak})).data;assert.equal(ws.tasks.find(t=>t.id===unfinished).week_id,next);assert(ws.activity.some(a=>a.object_id===unfinished&&a.details.includes('previous_deadline')));assert(JSON.parse(ws.reviews.find(r=>r.id===review).snapshot).some(t=>t.id===task&&t.status==='Completed'));});
 await check('Meeting MOM, attendees and idempotent action-to-task conversion',async()=>{meeting=await create('meetings',{title:'Validation meeting',date:'2026-10-08T19:00',agenda:'Review tests',discussion:'All paths reviewed',decisions:'Proceed with deployment',problems:'None',attendee_ids:[memberId]});action=await create('actions',{meeting_id:meeting,title:'Meeting follow-up',assignee_id:memberId,deadline:'2026-10-12',status:'To Do'});const first=await post('/api/workspace',{operation:'convert-action',id:action},malak),second=await post('/api/workspace',{operation:'convert-action',id:action},shahy);assert.equal(first.data.id,second.data.id);assert((await req('/api/workspace',{cookie:member})).data.attendees.some(a=>a.meeting_id===meeting&&a.user_id===memberId));});
 await check('R2 PDF upload, retrieval, versioning and invalid files',async()=>{const pdfBytes=Buffer.from('%PDF-1.4\nTest file\n%%EOF');const f=new FormData();f.set('file',new File([pdfBytes],'evidence.pdf',{type:'application/pdf'}));f.set('category','Reports');f.set('task_id',task);f.set('update_id',update);f.set('week_id',week);document=(await post('/api/documents',f,member,201)).data.id;const r=await req('/api/documents/'+document,{cookie:shahy});assert.deepEqual(Buffer.from(r.data),pdfBytes);const ws=(await req('/api/workspace',{cookie:malak})).data;const d=ws.documents.find(d=>d.id===document);const version=new FormData();version.set('file',new File([pdfBytes],'evidence-v2.pdf',{type:'application/pdf'}));version.set('category','Reports');version.set('family_id',d.family_id);await post('/api/documents',version,member,201);assert.equal((await req('/api/workspace',{cookie:member})).data.documents.filter(x=>x.family_id===d.family_id).length,2);const invalid=new FormData();invalid.set('file',new File(['not a pdf'],'bad.pdf'));await post('/api/documents',invalid,member,400);});
 await check('Team signup, login, Member task creation and shared Admin visibility',async()=>{
 const pass=randomBytes(16).toString('hex'),signup={name:'New Team Member',email:'newmember@test.invalid',password:pass,confirmPassword:pass};
 await post('/api/auth/signup',{...signup,role:'ADMIN'},'',400);
 await post('/api/auth/signup',{...signup,confirmPassword:'different-password'},'',400);
 await post('/api/auth/signup',signup,'',201);await post('/api/auth/signup',signup,'',409);
 const login=await post('/api/auth/login',{login:signup.email,password:pass});const cookie=login.res.headers.get('set-cookie').split(';')[0];const person=(await req('/api/workspace',{cookie})).data.user;assert.equal(person.role,'MEMBER');assert.equal(person.must_change,0);
 const own=await create('tasks',{...taskBody,title:'Test GPS Module',assignee_id:null},cookie);
 const assigned=await create('tasks',{...taskBody,title:'Created by member assigned to Malak',assignee_id:(await req('/api/workspace',{cookie:malak})).data.user.id},cookie);
 await req('/api/entities/tasks/'+own,{method:'PATCH',cookie,body:{title:'Test GPS Module updated',progress:50,status:'In Progress'}});
 await create('comments',{task_id:own,body:'GPS evidence recorded'},cookie);
 await create('updates',{week_id:week,task_id:own,description:'GPS tested'},cookie);
 const file=new FormData();file.set('file',new File(['%PDF-1.4\nGPS\n%%EOF'],'gps.pdf',{type:'application/pdf'}));file.set('category','Reports');file.set('task_id',own);const doc=(await post('/api/documents',file,cookie,201)).data.id;
 const m=(await req('/api/workspace',{cookie:malak})).data.user.id,h=(await req('/api/workspace',{cookie:shahy})).data.user.id;
 const mt=await create('tasks',{...taskBody,title:'Train YOLO Model',assignee_id:m},malak),ht=await create('tasks',{...taskBody,title:'Build AWS API',assignee_id:h},shahy);
 await req('/api/entities/tasks/'+own,{method:'PATCH',cookie,body:{status:'Completed',result:'GPS validated'}});
 for(const adminCookie of [malak,shahy]){const ws=(await req('/api/workspace',{cookie:adminCookie})).data;for(const id of [own,assigned,mt,ht])assert(ws.tasks.some(t=>t.id===id));assert.equal(ws.tasks.find(t=>t.id===own).created_by,person.id);assert.equal(ws.tasks.find(t=>t.id===own).assignee_id,person.id);assert.equal(ws.tasks.find(t=>t.id===assigned).assignee_id,m);assert(ws.documents.some(d=>d.id===doc));for(const type of ['tasks','comments','updates','documents'])assert(ws.activity.some(a=>a.actor_id===person.id&&a.object_type===type));assert.equal(ws.users.filter(u=>u.role==='ADMIN').length,2);const panel=await req('/admin',{cookie:adminCookie});assert(!new TextDecoder().decode(panel.data).includes('This page is only available to workspace administrators.'));}
 for(const path of ['/admin','/admin/users','/analytics']){const r=await req(path,{cookie});assert(new TextDecoder().decode(r.data).includes('Access Denied'));}
 await req('/api/entities/tasks/'+mt,{method:'PATCH',cookie,body:{progress:30},expected:403});
 await req('/api/entities/users/'+person.id,{method:'PATCH',cookie:malak,body:{role:'ADMIN'},expected:400});
 await post('/api/auth/logout',{},cookie);await req('/api/workspace',{cookie,expected:401});
 });
 await check('Task archiving preserves history, comments and files',async()=>{await req('/api/entities/tasks/'+task,{method:'DELETE',cookie:member,expected:403});await req('/api/entities/tasks/'+task,{method:'DELETE',cookie:malak});const ws=(await req('/api/workspace',{cookie:shahy})).data;assert(ws.tasks.find(t=>t.id===task).deleted_at);assert(ws.comments.some(c=>c.task_id===task));assert(ws.documents.some(d=>d.task_id===task));assert(ws.activity.some(a=>a.object_id===task&&a.action==='Archived task'));});
 await check('Professional project history PDF generation',async()=>{const r=await req('/api/export',{cookie:malak});assert.equal(r.res.headers.get('content-type'),'application/pdf');const bytes=Buffer.from(r.data);assert(bytes.subarray(0,8).toString().startsWith('%PDF-1.4'));assert(bytes.toString().includes('Weekly Reviews')&&bytes.toString().includes('Proceed with deployment'));writeFileSync('/tmp/icvsp-test-history.pdf',bytes);});
 await check('Notifications, logout, re-login and persistence',async()=>{const before=(await req('/api/workspace',{cookie:member})).data;assert(before.notifications.some(n=>n.title.startsWith('Task assigned')));await post('/api/workspace',{operation:'read-notifications'},member);assert((await req('/api/workspace',{cookie:member})).data.notifications.every(n=>n.read_at));await post('/api/auth/logout',{},member);await req('/api/workspace',{cookie:member,expected:401});const r=await post('/api/auth/login',{login:'testmember',password:passwords.changed});member=r.res.headers.get('set-cookie').split(';')[0];assert.equal((await req('/api/workspace',{cookie:member})).data.documents.length,before.documents.length);});
 await check('Disabling a member invalidates sessions',async()=>{await req('/api/entities/users/'+memberId,{method:'PATCH',cookie:malak,body:{active:0}});await req('/api/workspace',{cookie:member,expected:401});});
 console.log(JSON.stringify({passed:results.length,results},null,2));
}finally{await mf.dispose();}
