import {z} from 'zod';
import {resources} from './resources';
import {str,now,uid,stmt,db,one,all,audit,notify,passwordHash,taskAccess,fail} from './server';
const tables:Record<string,string>={assignee_id:'users',task_id:'tasks',week_id:'weekly_plans',month_id:'monthly_plans',milestone_id:'milestones',stage_id:'stages',meeting_id:'meetings',review_id:'weekly_reviews',update_id:'weekly_updates'};
export async function refs(data:any){for(const [key,table] of Object.entries(tables)){if(data[key]&&!await one(`SELECT id FROM ${table} WHERE id=?`,data[key]))fail(400,'Selected '+key.replace('_id','')+' does not exist');if(key==='assignee_id'&&data[key]&&!await one('SELECT id FROM users WHERE id=? AND active=1',data[key]))fail(400,'Assignee account is disabled');}}
export async function mutate(u:any,type:string,id:string|null,body:any){
 if(type==='users')return userMutation(u,id,body);
 const cfg=resources[type];if(!cfg)fail(404,'Unknown resource');if(cfg.admin&&u.role!=='ADMIN'&&type!=='tasks')fail(403,'Access Denied');
 let old:any=null;if(id){old=await one(`SELECT * FROM ${cfg.table} WHERE id=?`,id);if(!old)fail(404,'Record not found');if(type==='tasks')await taskAccess(u,id,true);if(['reviews','comments','updates'].includes(type))fail(400,'History entries are permanent. Add a new entry instead.');}
 let data:any;
 if(type==='tasks'&&id&&u.role!=='ADMIN'){data=z.object({title:str(240).optional(),description:z.string().max(12000).optional(),start_date:resources.tasks.schema.shape.start_date.optional(),deadline:resources.tasks.schema.shape.deadline.optional(),duration:resources.tasks.schema.shape.duration.optional(),priority:resources.tasks.schema.shape.priority.optional(),week_id:resources.tasks.schema.shape.week_id,month_id:resources.tasks.schema.shape.month_id,milestone_id:resources.tasks.schema.shape.milestone_id,stage_id:resources.tasks.schema.shape.stage_id,status:z.enum(['To Do','In Progress','Blocked','Completed','Delayed']).optional(),progress:z.coerce.number().int().min(0).max(100).optional(),delay_reason:z.string().max(12000).optional(),result:z.string().max(12000).optional()}).strict().parse(body);if(!Object.keys(data).length)fail(400,'No changes supplied');data={...Object.fromEntries(Object.keys(resources.tasks.schema.shape).map(k=>[k,old[k]])),...data};}
 else data=cfg.schema.parse(id?{...old,...body}:body);
 if(cfg.dates&&data.deadline<data.start_date)fail(400,'Deadline must be on or after the start date');await refs(data);
 const ops:any[]=[];const key=id||uid();const time=now();
 if(type==='tasks'){if(!id&&u.role!=='ADMIN'&&!data.assignee_id)data.assignee_id=u.id;if(data.status==='Completed')data.progress=100;else if(data.progress===100)fail(400,'Choose Completed when progress is 100%');if(data.status==='Delayed'&&!data.delay_reason.trim())fail(400,'Please explain the delay');data.completed_at=data.status==='Completed'?(old?.completed_at||time):null;data.updated_at=time;if(!id)data.created_by=u.id;}
 if(['updates','comments','reviews'].includes(type))data.author_id=u.id;
 if(type==='updates'&&data.task_id)await taskAccess(u,data.task_id,true);
 if(type==='comments')await taskAccess(u,data.task_id);
 if(type==='reviews')data.snapshot=JSON.stringify(await all('SELECT id,title,status,progress,delay_reason,assignee_id FROM tasks WHERE week_id=? AND deleted_at IS NULL',data.week_id));
 if(!id&&type!=='stages'&&type!=='actions')data.created_at=time;
 const keys=Object.keys(data);if(id)ops.push(stmt(`UPDATE ${cfg.table} SET ${keys.map(k=>k+'=?').join(',')} WHERE id=?`,...keys.map(k=>data[k]??null),id));else ops.push(stmt(`INSERT INTO ${cfg.table} (id,${keys.join(',')}) VALUES (${['id',...keys].map(()=>'?').join(',')})`,key,...keys.map(k=>data[k]??null)));
 const title=data.title||data.name||data.description?.slice(0,100)||data.body?.slice(0,100)||'Weekly review';
 ops.push(audit(u,id?'Updated':'Created',type,key,title,JSON.stringify({before:old?clean(old):null,after:data})));
 if(type==='tasks'&&data.assignee_id&&(!id||old.assignee_id!==data.assignee_id))ops.push(notify(data.assignee_id,'Task assigned: '+title,'tasks',key));
 if(type==='tasks'&&data.status==='Completed'&&old?.status!=='Completed'){for(const a of await all("SELECT id FROM users WHERE role='ADMIN' AND active=1"))ops.push(notify(a.id,'Task completed: '+title,'tasks',key));}
 if(type==='meetings'){for(const a of await all('SELECT id FROM users WHERE active=1'))ops.push(notify(a.id,id?'MOM updated: '+title:'New meeting: '+title,'meetings',key));if(Array.isArray(body.attendee_ids)){const attendeeIds=z.array(z.string().uuid()).max(100).parse(body.attendee_ids);ops.push(stmt('DELETE FROM meeting_attendees WHERE meeting_id=?',key));for(const aid of new Set(attendeeIds)){if(!await one('SELECT id FROM users WHERE id=?',aid))fail(400,'Unknown attendee');ops.push(stmt('INSERT INTO meeting_attendees (id,meeting_id,user_id) VALUES (?,?,?)',uid(),key,aid));}}}
 if(type==='comments'){const t=await one('SELECT assignee_id,title FROM tasks WHERE id=?',data.task_id);const recipients=new Set<string>();if(t.assignee_id&&t.assignee_id!==u.id)recipients.add(t.assignee_id);for(const a of await all('SELECT id,username FROM users WHERE active=1'))if(data.body.includes('@'+a.username)&&a.id!==u.id)recipients.add(a.id);for(const recipient of recipients)ops.push(notify(recipient,u.name+' commented on '+t.title,'tasks',data.task_id));}
 await db().batch(ops);return {id:key};
}
function clean(u:any){const {password_hash,...safe}=u;return safe;}
async function userMutation(u:any,id:string|null,body:any){if(u.role!=='ADMIN')fail(403,'Access Denied');const old=id?await one('SELECT * FROM users WHERE id=?',id):null;if(id&&!old)fail(404,'User not found');const b=z.object({name:str(200),username:z.string().regex(/^[a-z0-9._-]{3,40}$/),email:z.string().email(),role:z.enum(['ADMIN','MEMBER']),active:z.coerce.number().int().min(0).max(1).default(1),password:z.string().min(12).max(128).optional()}).parse({...old,...body});if(b.role==='ADMIN'&&!old?.locked_admin)fail(400,'Only Malak and Shahy can be Admins');if(old?.locked_admin&&(b.role!=='ADMIN'||b.active!==1||b.username!==old.username))fail(400,'Malak and Shahy must retain their usernames and active Admin access');if((!id||old?.password_hash==='unactivated'&&b.active===1)&&!b.password)fail(400,'Supply a temporary password of at least 12 characters');if(await one('SELECT id FROM users WHERE (username=? OR email=?) AND id!=?',b.username,b.email.toLowerCase(),id||''))fail(409,'Email or username already exists');
 const key=id||uid(),{password,...data}=b;data.email=data.email.toLowerCase();const values:any={...data};if(password){values.password_hash=await passwordHash(password);values.must_change=1;}const ops:any[]=[];if(id){const keys=Object.keys(values);ops.push(stmt(`UPDATE users SET ${keys.map(k=>k+'=?').join(',')} WHERE id=?`,...keys.map(k=>values[k]),id));if(password||b.active===0||b.role!==old.role)ops.push(stmt('DELETE FROM sessions WHERE user_id=?',id));}else{ops.push(stmt('INSERT INTO users (id,name,username,email,password_hash,role,active,must_change,created_at) VALUES (?,?,?,?,?,?,?,1,?)',key,b.name,b.username,b.email,values.password_hash,b.role,b.active,now()));}ops.push(audit(u,id?'Updated account':'Created account','users',key,b.name,JSON.stringify({name:b.name,role:b.role,active:b.active,passwordReset:!!password})));await db().batch(ops);return {id:key};}
export async function remove(u:any,type:string,id:string){if(u.role!=='ADMIN')fail(403,'Access Denied');if(type!=='tasks')fail(400,'Project history is permanent. Edit the record or disable the account instead.');const t=await taskAccess(u,id);await db().batch([stmt('UPDATE tasks SET deleted_at=?,updated_at=? WHERE id=?',now(),now(),id),audit(u,'Archived task','tasks',id,t.title,JSON.stringify(t))]);return {ok:true};}
