import {z} from 'zod';
import {safe,json,origin,requireUser,all,one,stmt,db,uid,now,notify,audit,fail,taskAccess} from '@/lib/server';
import {seed} from '@/lib/seed';
import {mutate} from '@/lib/mutations';
export const dynamic='force-dynamic';
export async function GET(req:Request){return safe(async()=>{const u=await requireUser(req);if(u.must_change)return json({user:u,force_password:true});
 const today=now().slice(0,10),soon=new Date(Date.now()+3*86400000).toISOString().slice(0,10);const due=await all("SELECT id,title,deadline FROM tasks WHERE assignee_id=? AND status!='Completed' AND deleted_at IS NULL AND deadline<=?",u.id,soon);const notifications=due.map(t=>stmt('INSERT OR IGNORE INTO notifications (id,user_id,title,object_type,object_id,created_at) VALUES (?,?,?,?,?,?)',`deadline:${u.id}:${t.id}:${t.deadline}:${t.deadline<today?'overdue':'upcoming'}`,u.id,(t.deadline<today?'Task overdue: ':'Deadline approaching: ')+t.title,'tasks',t.id,now()));if(notifications.length)await db().batch(notifications);
 const [users,tasks,weeks,months,milestones,stages,reviews,updates,meetings,attendees,actions,documents,comments,activity,notes,settings]=await Promise.all([
 all('SELECT id,name,username,email,role,active,locked_admin,avatar,must_change,created_at FROM users ORDER BY locked_admin DESC,name'),all('SELECT * FROM tasks ORDER BY created_at DESC'),all('SELECT * FROM weekly_plans ORDER BY start_date'),all('SELECT * FROM monthly_plans ORDER BY start_date'),all('SELECT * FROM milestones ORDER BY deadline'),all('SELECT * FROM stages ORDER BY position'),all('SELECT * FROM weekly_reviews ORDER BY created_at DESC'),all('SELECT * FROM weekly_updates ORDER BY created_at DESC'),all('SELECT * FROM meetings ORDER BY date DESC'),all('SELECT * FROM meeting_attendees'),all('SELECT * FROM meeting_actions'),all('SELECT id,name,mime,size,category,version,family_id,author_id,task_id,week_id,milestone_id,stage_id,meeting_id,review_id,update_id,created_at FROM documents ORDER BY created_at DESC'),all('SELECT * FROM comments ORDER BY created_at'),all("SELECT id,actor_id,action,object_type,object_id,title,details,created_at FROM activity_logs WHERE object_type!='users' OR ?='ADMIN' ORDER BY created_at DESC",u.role),all('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC',u.id),one('SELECT * FROM project_settings WHERE id=?','project')]);
 return json({user:u,users,tasks,weeks,months,milestones,stages,reviews,updates,meetings,attendees,actions,documents,comments,activity,notifications:notes,settings});});}
export async function POST(req:Request){return safe(async()=>{origin(req);const u=await requireUser(req);if(u.must_change)fail(403,'Change your temporary password first');const body:any=await req.json();
 if(body.operation==='read-notifications'){await stmt('UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL',now(),u.id).run();return json({ok:true});}
 if(body.operation==='profile'){const b=z.object({name:z.string().trim().min(1).max(200),avatar:z.string().max(3).default('')}).parse(body);await db().batch([stmt('UPDATE users SET name=?,avatar=? WHERE id=?',b.name,b.avatar,u.id),audit(u,'Updated profile','user',u.id,b.name)]);return json({ok:true});}
 if(u.role!=='ADMIN')fail(403,'Access Denied');
 if(body.operation==='seed')return json(await seed(u));
 if(body.operation==='convert-action'){const id=z.string().uuid().parse(body.id);const a=await one('SELECT * FROM meeting_actions WHERE id=?',id);if(!a)fail(404,'Action not found');if(a.task_id)return json({id:a.task_id});const key=uid(),time=now(),today=time.slice(0,10);const start=a.deadline<today?a.deadline:today;const results=await db().batch([stmt('INSERT INTO tasks (id,title,description,assignee_id,start_date,deadline,duration,priority,status,progress,created_by,created_at,updated_at) SELECT ?,title,?,assignee_id,?,deadline,1,\'Medium\',\'To Do\',0,?,?,? FROM meeting_actions WHERE id=? AND task_id IS NULL',key,'Action item from meeting '+a.meeting_id,start,u.id,time,time,id),stmt('UPDATE meeting_actions SET task_id=? WHERE id=? AND task_id IS NULL',key,id)]);if(!results[0].meta.changes)return json({id:(await one('SELECT task_id FROM meeting_actions WHERE id=?',id)).task_id});await audit(u,'Converted meeting action to task','tasks',key,a.title).run();if(a.assignee_id)await notify(a.assignee_id,'Task assigned: '+a.title,'tasks',key).run();return json({id:key});}
 if(body.operation==='carry-forward'){const b=z.object({week_id:z.string().uuid(),task_ids:z.array(z.string().uuid()).min(1).max(100)}).parse(body);const w=await one('SELECT * FROM weekly_plans WHERE id=?',b.week_id);if(!w)fail(404,'Week not found');const ops:any[]=[];for(const id of new Set(b.task_ids)){const t=await taskAccess(u,id);if(t.status==='Completed')fail(400,'Completed tasks cannot be carried forward');ops.push(stmt('UPDATE tasks SET week_id=?,month_id=?,start_date=?,deadline=?,updated_at=? WHERE id=?',w.id,w.month_id,w.start_date,w.deadline,now(),id),audit(u,'Carried task forward','tasks',id,t.title,JSON.stringify({previous_week:t.week_id,previous_deadline:t.deadline,new_week:w.id,new_deadline:w.deadline})));}await db().batch(ops);return json({ok:true});}
 fail(400,'Unknown operation');});}
